### ISSUE TITLE
datasets: urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

### ISSUE THREAD

**Issue by Bryan2Chow** [mengliu1998/DeeperGNN#3]
**Hi, Thx for your nice work!

I got this error (Actually, all datasets got the same error):**

$ bash run.sh
=====Cora=====
---Fiexd Splits---
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dagnn.py", line 84, in <module>
    dataset = get_planetoid_dataset(args.dataset, args.normalize_features)
  File "F:\PapersCode\DeeperGNN\DeeperGNN\datasets.py", line 9, in get_planetoid_dataset
    dataset = Planetoid(path, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\datasets\planetoid.py", line 55, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 89, in __init__
    self._download()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\datasets\planetoid.py", line 105, in download
    download_url('{}/{}'.format(self.url, name), self.raw_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\download.py", line 31, in download_url
    data = urllib.request.urlopen(url)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

**Then  I changed the DNS.  However, I got another error:**

$ bash run.sh
=====Cora=====
---Fiexd Splits---
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dagnn.py", line 84, in <module>
    dataset = get_planetoid_dataset(args.dataset, args.normalize_features)
  File "F:\PapersCode\DeeperGNN\DeeperGNN\datasets.py", line 9, in get_planetoid_dataset
    dataset = Planetoid(path, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\datasets\planetoid.py", line 31, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 82, in __init__
    self._download()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 118, in _download
    self.download()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\datasets\planetoid.py", line 45, in download
    download_url('{}/{}'.format(self.url, name), self.raw_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\download.py", line 31, in download_url
    data = urllib.request.urlopen(url)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒>

**I have found different solutions on the Internet, but nothing worked for me. 
I would appreciate it if u could help me. 
Thank you!**

**Comment by mengliu1998** [comment]
@Bryan2Chow Hi, thank you for your interest.

In your case, this seems to be some external connection problem. I am not able to figure it out.

Could you download the datasets manually?

**Comment by Bryan2Chow** [comment]
Thanks for your reply!
I can download the datasets one by one manually. But I am not sure exactly I can download all the datasets that the model required.
Could you please sent  the datasets to my email: bryan_chow@163.com   Or any other way you feel comfortable.
That would be a great！

**Comment by mengliu1998** [comment]
Sure. I have sent them to you.

Also, you can download it manually at [here](https://drive.google.com/file/d/1-0HlGQz6ndurCmGAlHT1vyH7tau_ZuP6/view?usp=sharing).

**Comment by Bryan2Chow** [comment]
Thanks a lot!
