### ISSUE TITLE
There is a problem when we run the dataset Cora

### ISSUE THREAD

**Issue by Heisenberg-Yin** [mengliu1998/DeeperGNN#5]
0%|          | 0/100 [00:00<?, ?run/s]Traceback (most recent call last):
  File "E:/machine learning/spectral and algebraic theory/20200814Myself/DeeperGNN-master/DeeperGNN/dagnn.py", line 113, in <module>
    run(dataset, Net(dataset), args.runs, args.epochs, args.lr, args.weight_decay, args.early_stopping, permute_masks, lcc=False)
  File "E:\machine learning\spectral and algebraic theory\20200814Myself\DeeperGNN-master\DeeperGNN\train_eval.py", line 121, in run
    eval_info = evaluate(model, data)
  File "E:\machine learning\spectral and algebraic theory\20200814Myself\DeeperGNN-master\DeeperGNN\train_eval.py", line 175, in evaluate
    pred = logits[mask].max(1)[1]
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

**Comment by mengliu1998** [comment]
@Heisenberg-Yin 

You can print 'mask', 'logits', and 'logits[mask]'(num_samples*num_class) to see if they are derived correctly.
